### ISSUE TITLE
Vectorize VEGAS over dimensionality

### ISSUE THREAD

**Issue by htoftevaag** [esa/torchquad#122]
# Feature

## Desired Behavior / Functionality

We would like to vectorize VEGAS over dimensionality to speed it up.

## What Needs to Be Done

In the files vegas_map.py and vegas_stratification.py there are several loops iterating over the dimension. These should be vectorized to speed up integration with vegas. This should be particularly beneficial for high-dimensional problems.

In particular, the following functions are good candidates:

- [ ] vegas_map.py - get_X
- [ ] vegas_map.py - get_Jac
- [ ] vegas_map.py - accumulate_weight
- [ ] vegas_map.py - _smooth_map
- [ ] vegas_map.py - update_map
- [ ] vegas_stratification.py - _get_indices

## How Can It Be Tested

All unit tests should still pass (they test error convergence)

A good way of testing runtime is by using the vegas_test.py in the tests folder. If called directly with `python vegas_test.py` it will print out a cprofile of the tests. Speedups should be particularly noticeable for high-dimensional problems.

**Comment by gomezzz** [comment]
@FHof I think you also did this, right?

**Comment by FHof** [comment]
No, I haven't vectorized the VEGASMap over the dimension everywhere, but this vectorization could be possible. 
I think the `_add_at_indices` function currently only works with 1D tensors, but it could be extended for multiple dimensions.
Here are the current `for` loops over the dimension:
https://github.com/esa/torchquad/blob/32a22f2ee88a106f7cfc6fd2f817f66e94861fa0/torchquad/integration/vegas_map.py#L58-L60
https://github.com/esa/torchquad/blob/32a22f2ee88a106f7cfc6fd2f817f66e94861fa0/torchquad/integration/vegas_map.py#L74-L76
https://github.com/esa/torchquad/blob/32a22f2ee88a106f7cfc6fd2f817f66e94861fa0/torchquad/integration/vegas_map.py#L111-L114
https://github.com/esa/torchquad/blob/32a22f2ee88a106f7cfc6fd2f817f66e94861fa0/torchquad/integration/vegas_map.py#L212-L275

From the functions listed in the issue description, I have only vectorized `VEGASStratification._get_indices` and `VEGASMap._smooth_map` over the dimension.
#
I mainly vectorized the code with respect to values depending on the number of evaluations. With a four-dimensional integrand and a high number of points, this made VEGAS about 300 times faster: https://github.com/FHof/torchquad/issues/13#issuecomment-1020210140

**Comment by gomezzz** [comment]
Ok, in any event, I think the performance should for now be quite a lot better. I will close it for now and we can reopen if we find it to be too slow at a later point. Thanks!
