### ISSUE TITLE
Add PyTorch Profiler to track performance

### ISSUE THREAD

**Issue by gomezzz** [esa/torchquad#129]
# Feature
## Desired Behavior / Functionality
Until now we have used cprofile to investigate performance of torchquad. However, especially for GPUs it may be interesting to start investigating with the new PyTorch profiler. Especially, as it has recently received [some upgrades]( https://pytorch.org/blog/pytorch-profiler-1.9-released/).

## What Needs to Be Done
- [ ] Set up things so that profiling with PyTorch profiler is easily doable
- [ ] Profile!
- [ ] Feel free to sum up your conclusions as to what optimization targets might be from this.
- [ ] (optionally) add a notebook or some code to run a performance analysis of torchquad using the profiler.

**Comment by gomezzz** [comment]
@FHof Do you think this issue still makes sense? Otherwise, I would close it :)

**Comment by FHof** [comment]
I think it only makes sense if you want to have the profiling code in this repository.
The profiling and benchmarking code which I have used are all in that folder of my fork: https://github.com/FHof/torchquad/tree/fritz/autoray/benchmarking_and_profiling 
(Here's a copy of it in case the above link stopped working: [benchmarking_and_profiling.zip](https://github.com/esa/torchquad/files/8478982/benchmarking_and_profiling.zip))
The profiling code is [in do_profile.py](https://github.com/FHof/torchquad/blob/83895637e9c4acd9382ed764640f1721788526a0/benchmarking_and_profiling/do_profile.py#L405) and a generated output for JAX, TensorFlow and PyTorch can be viewed in TensorBoard.
Example output for the profilers can be seen at https://github.com/FHof/torchquad/issues/13 and in my thesis.

**Comment by gomezzz** [comment]
Perfect thanks! I will close this for now then.
