### ISSUE TITLE
Fix wrong return type in docstrings

### ISSUE THREAD

**Issue by MartinBubel** [esa/torchquad#138]
Hi,
I would like to suggest that the docsrings of bascially all `.integrate` functions of the classes in `torchquad.integration` are updated as they are currently reading `Returns: float: Integral value`. However, the functions are actually returning an object of type `torch.Tensor`. Of course, this is neither a bug nor a big deal at all, but it results in the user getting warnings and complaints by the IDE/IntelliSense.<br>
If you agree that this would be a good idea / quality of life update then I can offer to do the job of creating a Pull Request.

By the way: `torchquad` is a cool package! Thanks for your work!

Best regards
Martin

**Comment by gomezzz** [comment]
Hi Martin! 

Thanks! Good to know, haven't noticed this before. :)

Sure, feel free to create a PR into the `develop` branch and we can get this fixed.
