### ISSUE TITLE
Add tests for JIT

### ISSUE THREAD

**Issue by gomezzz** [esa/torchquad#164]
# Feature
## Desired Behavior / Functionality
[Seems we are not testing JIT functionality](https://github.com/esa/torchquad/pull/141#issuecomment-1455757843), we should find a way to test it.

## What Needs to Be Done
- Test it :) , JIT can be used as described [here](https://torchquad.readthedocs.io/en/main/tutorial.html#compiling-the-integrate-method)

## How Can It Be Tested
🥁 with the tests

**Comment by ilan-gold** [comment]
Are there any pitfalls here as to why this hasn't been done yet?

**Comment by gomezzz** [comment]
> Are there any pitfalls here as to why this hasn't been done yet?

Don't think so. I think we didn't consider this could break before 🤔
