### ISSUE TITLE
Integrate function with parameters

### ISSUE THREAD

**Issue by omashkova** [esa/torchquad#187]
Hi, I would like to know whether there is functionality for integrating functions with parameters. For example, if one has a function

```
def func(alpha, x):
    return x**2 * alpha
```

how can one apply `Trapezoid` rule to integrate over `x`, for example? In the docs there is information about additional arguments of functions in `BaseIntegrator` class, but it seems like it is always set to `None` when applied to concrete methods. 

If there is no such option, one may add something like `args=(alpha,)` to `Trapezoid.integrate()` or any other method. 

Thanks in advance!

**Comment by gomezzz** [comment]
Hi @omashkova , thanks for the question!

So, this should already be implemented. 

Either you can use [this feature](https://torchquad.readthedocs.io/en/main/tutorial.html#multidimensional-vectorized-integrands) or maybe define your integrand can just be defined with a [lambda function](https://www.w3schools.com/python/python_lambda.asp) ?

More concretly,  the latter can be done via:

```py
import torchquad as tq

def func(alpha, x):
    return x**2 * alpha

tp = tq.Trapezoid()

tp.integrate(lambda x: func(alpha=3,x), dim=1, N=100)
```

this however, does not parallelize over different alpha. For that, you need the above linked feature.

Does this help? :)

**Comment by gomezzz** [comment]
Perfect 💪 I will close this for now then. :)
