### ISSUE TITLE
VEGAS is not available when installing via pip 

### ISSUE THREAD

**Issue by Saleh0694** [esa/torchquad#60]
Hello, 

I installed the package via pip and couldn't import VEGAS using:

```
from torchquad import VEGAS
```

I checked the installed package and the torchquad.integration module doesn't contain vegas.

**Comment by gomezzz** [comment]
Dear Saleh,
VEGAS is still in the process of being implemented (see also the open PR #59 for it). It will be available in the next version of torchquad, which we hope to finalize in May. The version in the PR is also not yet vectorized and tested rigorously so I would advise to wait for the next release.

**Comment by Saleh0694** [comment]
Thanks for the answer! I was confused because VEGAS is already in the documentation. Looking forward to the next release.

**Comment by gomezzz** [comment]
Yes, we will improve the documentation in that regard to have a version number for when features are available :) Thanks for the feedback!
