### ISSUE TITLE
VEGAS slow?

### ISSUE THREAD

**Issue by tsfloss** [esa/torchquad#77]
Hi!

First of all, thanks for starting this project!

I was tinkering about with the VEGAS integrator and noticed that its speed (both on CPU (pytorch automatically uses multiple cores, right?) and GPU) is nowhere near as fast as the standard python package for vegas (with vectorized integrands) on just a single core. Results do match.

Have you tested torchquad vs standard vegas and ran into the same?

Curious to hear what you think about this :)

**Comment by gomezzz** [comment]
Hey! 

Thanks for the feedback! :)

It's nice to see people using and comparing it! 

You are right that our implementation is comparatively a bit slow at the moment. Vectorization proved non-trivial in some cases, especially over the dimension. We will need to look into it more.

There are also some parameters, which require more tuning like # of vegas iterations and # of stratifications. 

Can you provide some details on the settings you used? Then I will include them in the profiling that we will be doing to identify the bottlenecks.  Of particular interest would be N, integrand and dimensionality.

One part that we were particularly struggling with is the weight accumulation in the vegas map here: https://github.com/esa/torchquad/blob/4e25083fc2fe9dc4464f946f1238a4d79254845f/torchquad/integration/vegas_map.py#L106

If you have any thoughts on vectorizing that function we will gladly try them!

**Comment by gomezzz** [comment]
Fixed in #137 , will be in the next release
