### ISSUE TITLE
Any support for more advanced quadrature methods (e.g. Legendre-Gauss quadrature)?

### ISSUE THREAD

**Issue by Karbo123** [esa/torchquad#78]
Thanks for releasing this great work for differentiable quadrature in pytorch!
I recently want to develop a new operator for more advanced convolution, but unfortunately this operator involves integrating a one dimensional function with unlimited bound (from  0 to +inf), and each evaluation of this function is rather time-consuming. I can do a change of variable of make it within range [-1, 1]. But the problem is, to reduce the number of evaluations, I may need to use a more accurate quadrature method. I find gauss quadrature is probably the most accurate method. The number of evaluations can be constant for the same operator. So I'm asking if there exists more accurate/advanced quadrature methods in torchquad? For example, Legendre-Gauss, Romberg, adaptive simpson, or any other?

**Comment by gomezzz** [comment]
Hi!

You can find all of the implemented methods here: https://torchquad.readthedocs.io/en/main/integration_methods.html

Sorry, but the mentioned ones are not yet implemented, might be in the future though. We decided to start simple and increase complexity step-by-step.
